//@version=5
//
// Author: benso87
// benso87.com
//
indicator(title='Benso Pendulum', shorttitle='BePu', format=format.price, precision=2, timeframe='', timeframe_gaps=true)

// Inputs
ma(source, length, type) =>
    switch type
        'SMA' => ta.sma(source, length)
        'EMA' => ta.ema(source, length)

rsiPeriod = input.int(14, minval=1, title='Period', group='RSI Settings', inline='1')
rsiSource = input.source(close, 'Source', group='RSI Settings', inline='1')
smoothLen = input.int(1, minval=1, title='Smooth Length', group='RSI Settings', inline='2')
smoothType = input.string('EMA', title='Smooth Type', options=['SMA', 'EMA', 'RMA', 'VWMA'], group='RSI Settings', inline='2')
signalPeriod = input.int(12, title='Signal Period', group='RSI Settings', inline='3')
signalType = input.string('EMA', title='Type', options=['SMA', 'EMA'], group='RSI Settings', inline='3')

rsiWidth = input.int(4, title='Line Width', minval=1, maxval=4, group='RSI Style', inline='1')
rsiDynColors = input.bool(true, title='Dynamic RSI Colors', group='RSI Style', inline='2')
rsiDefColor = input.color(#008eff, title='Default', group='RSI Style', inline='3')
rsiHighColor = input.color(#ff0014, title='High', group='RSI Style', inline='3')
rsiLowColor = input.color(#0bff00, title='Low', group='RSI Style', inline='3')

tagHigh = input.int(75, title='Tag High', inline='high', group='Tag Lines')
tagHighColor = input.color(#0bff00, title='', inline='high', group='Tag Lines')
tagLow = input.int(25, title='Tag Low', inline='low', group='Tag Lines')
tagLowColor = input.color(#ff0014, title='', inline='low', group='Tag Lines')
tagWidth = input.int(2, title='Line Width', group='Tag Lines')

fastSource = input.source(close, title='Source', group='Fast RSI')
fastLength = input.int(14, title='Length', minval=1, group='Fast RSI')
obLevel = input.int(80, title='Overbought Level', minval=0, maxval=100, group='Fast RSI')
osLevel = input.int(20, title='Oversold Level', minval=0, maxval=100, group='Fast RSI')
fastPeriod = input.int(21, title='Period', minval=1, group='Fast RSI')

useAlertHigh = input.bool(false, title='High Alert', group='User Alerts', inline='1')
alertHigh = input.int(62, title='', group='User Alerts', inline='1')
alertHighLineColor = input.color(color.yellow, title='Line', group='User Alerts', inline='1')
alertHighBgColor = input.color(color.new(#0bff00, 70), title='Background', group='User Alerts', inline='1')
useAlertLow = input.bool(false, title='Low Alert', group='User Alerts', inline='2')
alertLow = input.int(38, title='', group='User Alerts', inline='2')
alertLowLineColor = input.color(color.yellow, title='Line', group='User Alerts', inline='2')
alertLowBgColor = input.color(color.new(#ff0014, 70), title='Background', group='User Alerts', inline='2')

stochSource = input.source(close, title='Source', group='Stochastic')
periodK = input.int(14, title='K', minval=1, group='Stochastic')
periodD = input.int(3, title='D', minval=1, group='Stochastic')
smoothK = input.int(3, title='K Smoothing', minval=1, group='Stochastic')
smoothD = input.int(3, title='D Smoothing', minval=1, group='Stochastic')

showMACD = input.bool(false, title='Show MACD Histogram', group='MACD')
macdColor = input.color(color.new(color.gray, transp=80), title='Color', group='MACD')
macdSource = input.source(close, title='Source', group='MACD')
macdFastLength = input.int(14, title='Fast Length', minval=1, group='MACD')
macdSlowLength = input.int(26, title='Slow Length', minval=1, group='MACD')
macdSigLength = input.int(9, title='Signal Length', minval=1, maxval=50, group='MACD')
macdMASrcType = input.string('EMA', title='Oscillator Type', options=['EMA', 'SMA'], group='MACD')
macdMASigType = input.string('EMA', title='Signal Line Type', options=['EMA', 'SMA'], group='MACD')

showVBC = input.bool(false, title='Color Bars Based On Volume', group='Volume Bar Colors', inline='0')
showBuy = input.bool(true, title='High Buy Volume', inline='1', group='Volume Bar Colors')
highBuyColor = input.color(color.yellow, title='', inline='1', group='Volume Bar Colors')
showSell = input.bool(true, title='High Sell Volume', inline='2', group='Volume Bar Colors')
highSellColor = input.color(color.orange, title='', inline='2', group='Volume Bar Colors')
bsRatio = input.float(2, title='Buy/Sell Ratio (2 = 200%)', inline='3', group='Volume Bar Colors')
volRatio = input.float(2, title='Total Volume Ratio (2 = 200%)', inline='3', group='Volume Bar Colors')
volPeriod = input.int(20, title='Volume Moving Average', inline='4', group='Volume Bar Colors')


//////////////////////////////////////////////////////////////
// Calculations

// RSI calculations
up = ta.rma(math.max(ta.change(rsiSource), 0), rsiPeriod)
down = ta.rma(-math.min(ta.change(rsiSource), 0), rsiPeriod)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))

rsiColor = rsiDynColors and rsi > 50 ? rsiHighColor : rsiDynColors and rsi < 50 ? rsiLowColor : rsiDefColor

// Fast RSI calculations
fastUp = ta.rma(math.max(ta.change(fastSource), 0), fastPeriod)
fastDown = ta.rma(-math.min(ta.change(fastSource), 0), fastPeriod)
fastRSI = fastDown == 0 ? 100 : fastUp == 0 ? 100 - (100 / (1 + fastUp / fastDown))

// Stochastic calculations
k = ta.sma(ta.stoch(stochSource, high, low, periodK), smoothK)
d = ta.sma(k, periodD)

// MACD calculations
macdFast = ma(macdSource, macdFastLength, macdMASrcType)
macdSlow = ma(macdSource, macdSlowLength, macdMASrcType)
macd = macdFast - macdSlow

macdSignal = ma(macd, macdSigLength, macdMASigType)
macdHist = macd - macdSignal

// Volume bar color calculations
buyVol = high == low ? 0 : volume * (close - low) / (high - low)
sellVol = high == low ? 0 : volume * (high - close) / (high - low)

highVol = volume >= volRatio * ta.sma(volume, volPeriod)

highBuy = showVBC and showBuy and highVol ? buyVol >= (bsRatio * buyVol[1]) and buyVol > sellVol : na
highSell = showVBC and showSell and highVol ? sellVol >= (bsRatio * sellVol[1]) and sellVol > buyVol : na

// Alert background colors
backgroundColor = if ((rsi >= alertHigh) and useAlertHigh)
    alertHighBgColor
else if ((rsi <= alertLow) and useAlertLow)
	alertLowBgColor
else
	color(na)


//////////////////////////////////////////////////////////////
// Plots

// RSI
plot(rsi, 'RSI', color=rsiColor, linewidth=rsiWidth)

// Tag lines
rsiTagHigh = hline(tagHigh, 'Tag High', color=tagHighColor, linestyle=hline.style_solid, linewidth=tagWidth)
rsiTagLow = hline(tagLow, 'Tag Low', color=tagLowColor, linestyle=hline.style_solid, linewidth=tagWidth)
rsiMidLine = hline(50, 'Mid Line', color=color.new(#aaaaaa, transp=50), linestyle=hline.style_dashed)

// MACD
plot(showMACD ? macdHist + 50 : na, title='MACD', style=plot.style_columns, color=macdColor, histbase=50)

// User Alert Levels
rsiAlertHigh = hline(useAlertHigh ? alertHigh : na, 'User Alert High', color=alertHighLineColor, linestyle=hline.style_dotted)
rsiAlertLow = hline(useAlertLow ? alertLow : na, 'User Alert Low', color=alertLowLineColor, linestyle=hline.style_dotted)

// Volume bar colors
barcolor(highBuy ? highBuyColor : highSell ? highSellColor : na)

// Background color
bgcolor(backgroundColor)


//////////////////////////////////////////////////////////////
// Alerts

alertcondition(rsi >= alertHigh, title='Custom Alert High', message='RSI above custom alert level')
alertcondition(rsi <= alertLow, title='Custom Alert Low', message='RSI below custom alert level')